[mypy]
# mypy configurations: http://bit.ly/2zEl9WI
allow_redefinition = False
check_untyped_defs = True
disallow_any_explicit = True
disallow_any_generics = True
disallow_untyped_calls = True
disallow_incomplete_defs = True
ignore_errors = False
ignore_missing_imports = True
implicit_reexport = False
local_partial_types = True
strict_optional = True
strict_equality = True
no_implicit_optional = True
warn_no_return = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True
warn_unreachable = True
plugins = returns.contrib.mypy.returns_plugin

[flake8]
# Base flake8 configuration:
# https://flake8.pycqa.org/en/latest/user/configuration.html
format = wemake
show-source = true
statistics = false
doctests = true

# darglint configuration:
# https://github.com/terrencepreilly/darglint
strictness = long
docstring-style = numpy

# Plugins:
max-complexity = 6
max-line-length = 80

# Disable some pydocstyle checks:
# Exclude some pydoctest checks globally:
ignore = D100, D104, D106, D401, W504, X100, RST303, RST304, DAR103, DAR203

# Excluding some directories:
exclude =
  .git
  __pycache__
  .venv
  .eggs
  *.egg

